---
apiVersion: v1
kind: Pod
metadata:
  name: mongo-cli
  labels:
    app: mongo-cli
spec:
  containers:
  - name: mongo-cli
    image: mongo:3.2
    command: ["/bin/sleep", "infinity"]
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
